:bug: IF-10137 Fix to return error when update of firewall is failed
nttcom/terraform-provider-fic pull request #28
Opened 2023-04-25 07:49 UTC by sugimo-s

* fic/resource_eri_firewall_component.go
  - FIC-FWの更新API呼出処理（updateFirewall関数）について戻り値のエラー判定処理を追加
  - rules, customApplications, applicationSets, routingGroupSettingsについて宣言時の値を空リストに修正
* fic/resource_eri_firewall_component_v1_test.go
  - パラメーターOperationStatusの値が "Completed"のときも FIC-FWは削除されたとみなすよう修正

2023-04-25 08:28 UTC, NaoShark requested changes
https://github.com/nttcom/terraform-provider-fic/blob/master/fic/resource_eri_firewall_component.go#L322 の `nat` が正しくは `firewall` になります。
修正と水平展開をお願いしてもよろしいでしょうか？

2023-04-25 08:28 UTC, NaoShark commented on fic/resource_eri_firewall_component.go
> +		}
```suggestion
		if err := updateFirewall(d, meta); err != nil {
			return fmt.Errorf("Error updating firewall component: %s", err)
		}
```
ワンラインで書いていただいてもよろしいでしょうか？

2023-04-26 00:14 UTC, sugimo-s commented on fic/resource_eri_firewall_component.go
> +		}
ご指摘ありがとうございます。updateFirewall関数を呼んでいるもう一箇所のほうも同じ修正をしておきます。

2023-04-26 00:15 UTC, sugimo-s commented
> https://github.com/nttcom/terraform-provider-fic/blob/master/fic/resource_eri_firewall_component.go#L322 の `nat` が正しくは `firewall` になります。 修正と水平展開をお願いしてもよろしいでしょうか？

了解しました。エラーメッセージを "Error updating firewall component" に修正します。
fic/resource_eri_firewall_component.goについて点検し、他に不適切なメッセージは見当たりませんでした。

2023-04-26 00:56 UTC, a-oi-xon approved these changes

2023-04-26 02:11 UTC, NaoShark approved these changes

2023-04-26 02:27 UTC, merged